//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-10-31 09:04:30 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：CategoryEntity 
    /// </summary>
    [Serializable()]
    public partial class CategoryEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CategoryID { get; set; }

                    
		/// <summary>
		/// nvarchar:
		/// </summary>	
                 
		public string Name { get; set; }

                    
		/// <summary>
		/// nvarchar:
		/// </summary>	
                 
		public string Code { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? ParentID { get; set; }

                    
		/// <summary>
		/// nvarchar:
		/// </summary>	
                 
		public string CategoryPath { get; set; }

                    
		/// <summary>
		/// tinyint:
		/// </summary>	
                 
		public byte? Depth { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? SortNum { get; set; }

                    
		/// <summary>
		/// nvarchar:
		/// </summary>	
                 
		public string ImagePath { get; set; }

                    
		/// <summary>
		/// tinyint:
		/// </summary>	
                 
		public byte? IsHidden { get; set; }

           
    }    
}
	