//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-10-31 09:04:30 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：MemberEntity 
    /// </summary>
    [Serializable()]
    public partial class MemberEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Mobile { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Sex { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? BornDate { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Pwd { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string OpenId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string HeadIcon { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string NikeName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AddressInfo { get; set; }

           
    }    
}
	