//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-10-31 09:04:30 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：ProductEntity 
    /// </summary>
    [Serializable()]
    public partial class ProductEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProductId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProductNO { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProductUnit { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string ProductDescription { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? ProductStatus { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProductCategoryId { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? ProductPrice { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? ProductCostPrice { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? ProductStock { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string FaceImag { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? ProductType { get; set; }

           
    }    
}
	